/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RepertoireRouteImport } from './routes/repertoire'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises/$exerciseId'
import { Route as ExercisesNewRouteImport } from './routes/exercises/new'
import { Route as RepertoireRepertoireIdRouteImport } from './routes/repertoire/$repertoireId'
import { Route as RepertoireSearchRouteImport } from './routes/repertoire/search'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as SessionsNewRouteImport } from './routes/sessions/new'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates/$templateId'
import { Route as TemplatesNewRouteImport } from './routes/templates/new'
import { Route as ExercisesExerciseIdEditRouteImport } from './routes/exercises/$exerciseId_.edit'
import { Route as RepertoireRepertoireIdEditRouteImport } from './routes/repertoire/$repertoireId_.edit'
import { Route as SessionsSessionIdEditRouteImport } from './routes/sessions/$sessionId_.edit'
import { Route as TemplatesTemplateIdEditRouteImport } from './routes/templates/$templateId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertoireRoute = RepertoireRouteImport.update({
  id: '/repertoire',
  path: '/repertoire',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/$exerciseId',
  path: '/$exerciseId',
  getParentRoute: () => ExercisesRoute,
} as any)
const ExercisesNewRoute = ExercisesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ExercisesRoute,
} as any)
const RepertoireRepertoireIdRoute = RepertoireRepertoireIdRouteImport.update({
  id: '/$repertoireId',
  path: '/$repertoireId',
  getParentRoute: () => RepertoireRoute,
} as any)
const RepertoireSearchRoute = RepertoireSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => RepertoireRoute,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SessionsRoute,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TemplatesRoute,
} as any)
const ExercisesExerciseIdEditRoute = ExercisesExerciseIdEditRouteImport.update({
  id: '/$exerciseId_/edit',
  path: '/$exerciseId/edit',
  getParentRoute: () => ExercisesRoute,
} as any)
const RepertoireRepertoireIdEditRoute =
  RepertoireRepertoireIdEditRouteImport.update({
    id: '/$repertoireId_/edit',
    path: '/$repertoireId/edit',
    getParentRoute: () => RepertoireRoute,
  } as any)
const SessionsSessionIdEditRoute = SessionsSessionIdEditRouteImport.update({
  id: '/$sessionId_/edit',
  path: '/$sessionId/edit',
  getParentRoute: () => SessionsRoute,
} as any)
const TemplatesTemplateIdEditRoute = TemplatesTemplateIdEditRouteImport.update({
  id: '/$templateId_/edit',
  path: '/$templateId/edit',
  getParentRoute: () => TemplatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/repertoire': typeof RepertoireRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/repertoire/$repertoireId': typeof RepertoireRepertoireIdRoute
  '/repertoire/search': typeof RepertoireSearchRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/sessions/': typeof SessionsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/exercises/$exerciseId/edit': typeof ExercisesExerciseIdEditRoute
  '/repertoire/$repertoireId/edit': typeof RepertoireRepertoireIdEditRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionIdEditRoute
  '/templates/$templateId/edit': typeof TemplatesTemplateIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/repertoire': typeof RepertoireRouteWithChildren
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/repertoire/$repertoireId': typeof RepertoireRepertoireIdRoute
  '/repertoire/search': typeof RepertoireSearchRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/sessions': typeof SessionsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/exercises/$exerciseId/edit': typeof ExercisesExerciseIdEditRoute
  '/repertoire/$repertoireId/edit': typeof RepertoireRepertoireIdEditRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionIdEditRoute
  '/templates/$templateId/edit': typeof TemplatesTemplateIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/repertoire': typeof RepertoireRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/repertoire/$repertoireId': typeof RepertoireRepertoireIdRoute
  '/repertoire/search': typeof RepertoireSearchRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/sessions/': typeof SessionsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/exercises/$exerciseId_/edit': typeof ExercisesExerciseIdEditRoute
  '/repertoire/$repertoireId_/edit': typeof RepertoireRepertoireIdEditRoute
  '/sessions/$sessionId_/edit': typeof SessionsSessionIdEditRoute
  '/templates/$templateId_/edit': typeof TemplatesTemplateIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/exercises'
    | '/library'
    | '/login'
    | '/repertoire'
    | '/sessions'
    | '/templates'
    | '/exercises/$exerciseId'
    | '/exercises/new'
    | '/repertoire/$repertoireId'
    | '/repertoire/search'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/sessions/'
    | '/templates/'
    | '/exercises/$exerciseId/edit'
    | '/repertoire/$repertoireId/edit'
    | '/sessions/$sessionId/edit'
    | '/templates/$templateId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/exercises'
    | '/library'
    | '/login'
    | '/repertoire'
    | '/exercises/$exerciseId'
    | '/exercises/new'
    | '/repertoire/$repertoireId'
    | '/repertoire/search'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/sessions'
    | '/templates'
    | '/exercises/$exerciseId/edit'
    | '/repertoire/$repertoireId/edit'
    | '/sessions/$sessionId/edit'
    | '/templates/$templateId/edit'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/exercises'
    | '/library'
    | '/login'
    | '/repertoire'
    | '/sessions'
    | '/templates'
    | '/exercises/$exerciseId'
    | '/exercises/new'
    | '/repertoire/$repertoireId'
    | '/repertoire/search'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/sessions/'
    | '/templates/'
    | '/exercises/$exerciseId_/edit'
    | '/repertoire/$repertoireId_/edit'
    | '/sessions/$sessionId_/edit'
    | '/templates/$templateId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  ExercisesRoute: typeof ExercisesRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  RepertoireRoute: typeof RepertoireRouteWithChildren
  SessionsRoute: typeof SessionsRouteWithChildren
  TemplatesRoute: typeof TemplatesRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertoire': {
      id: '/repertoire'
      path: '/repertoire'
      fullPath: '/repertoire'
      preLoaderRoute: typeof RepertoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/exercises/new': {
      id: '/exercises/new'
      path: '/new'
      fullPath: '/exercises/new'
      preLoaderRoute: typeof ExercisesNewRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/repertoire/$repertoireId': {
      id: '/repertoire/$repertoireId'
      path: '/$repertoireId'
      fullPath: '/repertoire/$repertoireId'
      preLoaderRoute: typeof RepertoireRepertoireIdRouteImport
      parentRoute: typeof RepertoireRoute
    }
    '/repertoire/search': {
      id: '/repertoire/search'
      path: '/search'
      fullPath: '/repertoire/search'
      preLoaderRoute: typeof RepertoireSearchRouteImport
      parentRoute: typeof RepertoireRoute
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/exercises/$exerciseId_/edit': {
      id: '/exercises/$exerciseId_/edit'
      path: '/$exerciseId/edit'
      fullPath: '/exercises/$exerciseId/edit'
      preLoaderRoute: typeof ExercisesExerciseIdEditRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/repertoire/$repertoireId_/edit': {
      id: '/repertoire/$repertoireId_/edit'
      path: '/$repertoireId/edit'
      fullPath: '/repertoire/$repertoireId/edit'
      preLoaderRoute: typeof RepertoireRepertoireIdEditRouteImport
      parentRoute: typeof RepertoireRoute
    }
    '/sessions/$sessionId_/edit': {
      id: '/sessions/$sessionId_/edit'
      path: '/$sessionId/edit'
      fullPath: '/sessions/$sessionId/edit'
      preLoaderRoute: typeof SessionsSessionIdEditRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/templates/$templateId_/edit': {
      id: '/templates/$templateId_/edit'
      path: '/$templateId/edit'
      fullPath: '/templates/$templateId/edit'
      preLoaderRoute: typeof TemplatesTemplateIdEditRouteImport
      parentRoute: typeof TemplatesRoute
    }
  }
}

interface ExercisesRouteChildren {
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  ExercisesNewRoute: typeof ExercisesNewRoute
  ExercisesExerciseIdEditRoute: typeof ExercisesExerciseIdEditRoute
}

const ExercisesRouteChildren: ExercisesRouteChildren = {
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  ExercisesNewRoute: ExercisesNewRoute,
  ExercisesExerciseIdEditRoute: ExercisesExerciseIdEditRoute,
}

const ExercisesRouteWithChildren = ExercisesRoute._addFileChildren(
  ExercisesRouteChildren,
)

interface RepertoireRouteChildren {
  RepertoireRepertoireIdRoute: typeof RepertoireRepertoireIdRoute
  RepertoireSearchRoute: typeof RepertoireSearchRoute
  RepertoireRepertoireIdEditRoute: typeof RepertoireRepertoireIdEditRoute
}

const RepertoireRouteChildren: RepertoireRouteChildren = {
  RepertoireRepertoireIdRoute: RepertoireRepertoireIdRoute,
  RepertoireSearchRoute: RepertoireSearchRoute,
  RepertoireRepertoireIdEditRoute: RepertoireRepertoireIdEditRoute,
}

const RepertoireRouteWithChildren = RepertoireRoute._addFileChildren(
  RepertoireRouteChildren,
)

interface SessionsRouteChildren {
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsNewRoute: typeof SessionsNewRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SessionsSessionIdEditRoute: typeof SessionsSessionIdEditRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsNewRoute: SessionsNewRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SessionsSessionIdEditRoute: SessionsSessionIdEditRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  TemplatesNewRoute: typeof TemplatesNewRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TemplatesTemplateIdEditRoute: typeof TemplatesTemplateIdEditRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  TemplatesNewRoute: TemplatesNewRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  TemplatesTemplateIdEditRoute: TemplatesTemplateIdEditRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  ExercisesRoute: ExercisesRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  RepertoireRoute: RepertoireRouteWithChildren,
  SessionsRoute: SessionsRouteWithChildren,
  TemplatesRoute: TemplatesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
