/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/__root'
import { Route as IndexRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/index'
import { Route as ExercisesRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/exercises'
import { Route as LibraryRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/library'
import { Route as LoginRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/login'
import { Route as RepertoireRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/repertoire'
import { Route as SessionsRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/sessions'
import { Route as SettingsRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/settings'
import { Route as TemplatesRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/templates'
import { Route as ExercisesExerciseIdRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/exercises/$exerciseId'
import { Route as ExercisesNewRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/exercises/new'
import { Route as ExercisesOwnedRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/exercises/owned'
import { Route as ExercisesSearchRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/exercises/search'
import { Route as RepertoireRepertoireIdRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/repertoire/$repertoireId'
import { Route as RepertoireOwnedRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/repertoire/owned'
import { Route as RepertoireSearchRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/repertoire/search'
import { Route as SessionsIndexRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/sessions/index'
import { Route as SessionsSessionIdRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/sessions/$sessionId'
import { Route as SessionsNewRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/sessions/new'
import { Route as TemplatesIndexRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/templates/index'
import { Route as TemplatesTemplateIdRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/templates/$templateId'
import { Route as TemplatesNewRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/templates/new'
import { Route as ExercisesExerciseId_DoteditRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/exercises/$exerciseId_.edit'
import { Route as RepertoireRepertoireId_DoteditRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/repertoire/$repertoireId_.edit'
import { Route as SessionsSessionId_DoteditRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/sessions/$sessionId_.edit'
import { Route as TemplatesTemplateId_DoteditRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/templates/$templateId_.edit'
import { Route as RepertoireRepertoireId_DotchildrenDotnewRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/repertoire/$repertoireId_.children.new'
import { Route as RepertoireRepertoireId_DotexcerptsDotnewRouteImport } from './../../../node_modules/@music-practice-buddy/core/src/routes/repertoire/$repertoireId_.excerpts.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertoireRoute = RepertoireRouteImport.update({
  id: '/repertoire',
  path: '/repertoire',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/$exerciseId',
  path: '/$exerciseId',
  getParentRoute: () => ExercisesRoute,
} as any)
const ExercisesNewRoute = ExercisesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ExercisesRoute,
} as any)
const ExercisesOwnedRoute = ExercisesOwnedRouteImport.update({
  id: '/owned',
  path: '/owned',
  getParentRoute: () => ExercisesRoute,
} as any)
const ExercisesSearchRoute = ExercisesSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ExercisesRoute,
} as any)
const RepertoireRepertoireIdRoute = RepertoireRepertoireIdRouteImport.update({
  id: '/$repertoireId',
  path: '/$repertoireId',
  getParentRoute: () => RepertoireRoute,
} as any)
const RepertoireOwnedRoute = RepertoireOwnedRouteImport.update({
  id: '/owned',
  path: '/owned',
  getParentRoute: () => RepertoireRoute,
} as any)
const RepertoireSearchRoute = RepertoireSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => RepertoireRoute,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SessionsRoute,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TemplatesRoute,
} as any)
const ExercisesExerciseId_DoteditRoute =
  ExercisesExerciseId_DoteditRouteImport.update({
    id: '/$exerciseId_/edit',
    path: '/$exerciseId/edit',
    getParentRoute: () => ExercisesRoute,
  } as any)
const RepertoireRepertoireId_DoteditRoute =
  RepertoireRepertoireId_DoteditRouteImport.update({
    id: '/$repertoireId_/edit',
    path: '/$repertoireId/edit',
    getParentRoute: () => RepertoireRoute,
  } as any)
const SessionsSessionId_DoteditRoute =
  SessionsSessionId_DoteditRouteImport.update({
    id: '/$sessionId_/edit',
    path: '/$sessionId/edit',
    getParentRoute: () => SessionsRoute,
  } as any)
const TemplatesTemplateId_DoteditRoute =
  TemplatesTemplateId_DoteditRouteImport.update({
    id: '/$templateId_/edit',
    path: '/$templateId/edit',
    getParentRoute: () => TemplatesRoute,
  } as any)
const RepertoireRepertoireId_DotchildrenDotnewRoute =
  RepertoireRepertoireId_DotchildrenDotnewRouteImport.update({
    id: '/$repertoireId_/children/new',
    path: '/$repertoireId/children/new',
    getParentRoute: () => RepertoireRoute,
  } as any)
const RepertoireRepertoireId_DotexcerptsDotnewRoute =
  RepertoireRepertoireId_DotexcerptsDotnewRouteImport.update({
    id: '/$repertoireId_/excerpts/new',
    path: '/$repertoireId/excerpts/new',
    getParentRoute: () => RepertoireRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/repertoire': typeof RepertoireRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/exercises/owned': typeof ExercisesOwnedRoute
  '/exercises/search': typeof ExercisesSearchRoute
  '/repertoire/$repertoireId': typeof RepertoireRepertoireIdRoute
  '/repertoire/owned': typeof RepertoireOwnedRoute
  '/repertoire/search': typeof RepertoireSearchRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/sessions/': typeof SessionsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/exercises/$exerciseId/edit': typeof ExercisesExerciseId_DoteditRoute
  '/repertoire/$repertoireId/edit': typeof RepertoireRepertoireId_DoteditRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionId_DoteditRoute
  '/templates/$templateId/edit': typeof TemplatesTemplateId_DoteditRoute
  '/repertoire/$repertoireId/children/new': typeof RepertoireRepertoireId_DotchildrenDotnewRoute
  '/repertoire/$repertoireId/excerpts/new': typeof RepertoireRepertoireId_DotexcerptsDotnewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/repertoire': typeof RepertoireRouteWithChildren
  '/settings': typeof SettingsRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/exercises/owned': typeof ExercisesOwnedRoute
  '/exercises/search': typeof ExercisesSearchRoute
  '/repertoire/$repertoireId': typeof RepertoireRepertoireIdRoute
  '/repertoire/owned': typeof RepertoireOwnedRoute
  '/repertoire/search': typeof RepertoireSearchRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/sessions': typeof SessionsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/exercises/$exerciseId/edit': typeof ExercisesExerciseId_DoteditRoute
  '/repertoire/$repertoireId/edit': typeof RepertoireRepertoireId_DoteditRoute
  '/sessions/$sessionId/edit': typeof SessionsSessionId_DoteditRoute
  '/templates/$templateId/edit': typeof TemplatesTemplateId_DoteditRoute
  '/repertoire/$repertoireId/children/new': typeof RepertoireRepertoireId_DotchildrenDotnewRoute
  '/repertoire/$repertoireId/excerpts/new': typeof RepertoireRepertoireId_DotexcerptsDotnewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/repertoire': typeof RepertoireRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/exercises/owned': typeof ExercisesOwnedRoute
  '/exercises/search': typeof ExercisesSearchRoute
  '/repertoire/$repertoireId': typeof RepertoireRepertoireIdRoute
  '/repertoire/owned': typeof RepertoireOwnedRoute
  '/repertoire/search': typeof RepertoireSearchRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/sessions/': typeof SessionsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/exercises/$exerciseId_/edit': typeof ExercisesExerciseId_DoteditRoute
  '/repertoire/$repertoireId_/edit': typeof RepertoireRepertoireId_DoteditRoute
  '/sessions/$sessionId_/edit': typeof SessionsSessionId_DoteditRoute
  '/templates/$templateId_/edit': typeof TemplatesTemplateId_DoteditRoute
  '/repertoire/$repertoireId_/children/new': typeof RepertoireRepertoireId_DotchildrenDotnewRoute
  '/repertoire/$repertoireId_/excerpts/new': typeof RepertoireRepertoireId_DotexcerptsDotnewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises'
    | '/library'
    | '/login'
    | '/repertoire'
    | '/sessions'
    | '/settings'
    | '/templates'
    | '/exercises/$exerciseId'
    | '/exercises/new'
    | '/exercises/owned'
    | '/exercises/search'
    | '/repertoire/$repertoireId'
    | '/repertoire/owned'
    | '/repertoire/search'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/sessions/'
    | '/templates/'
    | '/exercises/$exerciseId/edit'
    | '/repertoire/$repertoireId/edit'
    | '/sessions/$sessionId/edit'
    | '/templates/$templateId/edit'
    | '/repertoire/$repertoireId/children/new'
    | '/repertoire/$repertoireId/excerpts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises'
    | '/library'
    | '/login'
    | '/repertoire'
    | '/settings'
    | '/exercises/$exerciseId'
    | '/exercises/new'
    | '/exercises/owned'
    | '/exercises/search'
    | '/repertoire/$repertoireId'
    | '/repertoire/owned'
    | '/repertoire/search'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/sessions'
    | '/templates'
    | '/exercises/$exerciseId/edit'
    | '/repertoire/$repertoireId/edit'
    | '/sessions/$sessionId/edit'
    | '/templates/$templateId/edit'
    | '/repertoire/$repertoireId/children/new'
    | '/repertoire/$repertoireId/excerpts/new'
  id:
    | '__root__'
    | '/'
    | '/exercises'
    | '/library'
    | '/login'
    | '/repertoire'
    | '/sessions'
    | '/settings'
    | '/templates'
    | '/exercises/$exerciseId'
    | '/exercises/new'
    | '/exercises/owned'
    | '/exercises/search'
    | '/repertoire/$repertoireId'
    | '/repertoire/owned'
    | '/repertoire/search'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/templates/$templateId'
    | '/templates/new'
    | '/sessions/'
    | '/templates/'
    | '/exercises/$exerciseId_/edit'
    | '/repertoire/$repertoireId_/edit'
    | '/sessions/$sessionId_/edit'
    | '/templates/$templateId_/edit'
    | '/repertoire/$repertoireId_/children/new'
    | '/repertoire/$repertoireId_/excerpts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesRoute: typeof ExercisesRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  RepertoireRoute: typeof RepertoireRouteWithChildren
  SessionsRoute: typeof SessionsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertoire': {
      id: '/repertoire'
      path: '/repertoire'
      fullPath: '/repertoire'
      preLoaderRoute: typeof RepertoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/exercises/new': {
      id: '/exercises/new'
      path: '/new'
      fullPath: '/exercises/new'
      preLoaderRoute: typeof ExercisesNewRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/exercises/owned': {
      id: '/exercises/owned'
      path: '/owned'
      fullPath: '/exercises/owned'
      preLoaderRoute: typeof ExercisesOwnedRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/exercises/search': {
      id: '/exercises/search'
      path: '/search'
      fullPath: '/exercises/search'
      preLoaderRoute: typeof ExercisesSearchRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/repertoire/$repertoireId': {
      id: '/repertoire/$repertoireId'
      path: '/$repertoireId'
      fullPath: '/repertoire/$repertoireId'
      preLoaderRoute: typeof RepertoireRepertoireIdRouteImport
      parentRoute: typeof RepertoireRoute
    }
    '/repertoire/owned': {
      id: '/repertoire/owned'
      path: '/owned'
      fullPath: '/repertoire/owned'
      preLoaderRoute: typeof RepertoireOwnedRouteImport
      parentRoute: typeof RepertoireRoute
    }
    '/repertoire/search': {
      id: '/repertoire/search'
      path: '/search'
      fullPath: '/repertoire/search'
      preLoaderRoute: typeof RepertoireSearchRouteImport
      parentRoute: typeof RepertoireRoute
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/exercises/$exerciseId_/edit': {
      id: '/exercises/$exerciseId_/edit'
      path: '/$exerciseId/edit'
      fullPath: '/exercises/$exerciseId/edit'
      preLoaderRoute: typeof ExercisesExerciseId_DoteditRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/repertoire/$repertoireId_/edit': {
      id: '/repertoire/$repertoireId_/edit'
      path: '/$repertoireId/edit'
      fullPath: '/repertoire/$repertoireId/edit'
      preLoaderRoute: typeof RepertoireRepertoireId_DoteditRouteImport
      parentRoute: typeof RepertoireRoute
    }
    '/sessions/$sessionId_/edit': {
      id: '/sessions/$sessionId_/edit'
      path: '/$sessionId/edit'
      fullPath: '/sessions/$sessionId/edit'
      preLoaderRoute: typeof SessionsSessionId_DoteditRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/templates/$templateId_/edit': {
      id: '/templates/$templateId_/edit'
      path: '/$templateId/edit'
      fullPath: '/templates/$templateId/edit'
      preLoaderRoute: typeof TemplatesTemplateId_DoteditRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/repertoire/$repertoireId_/children/new': {
      id: '/repertoire/$repertoireId_/children/new'
      path: '/$repertoireId/children/new'
      fullPath: '/repertoire/$repertoireId/children/new'
      preLoaderRoute: typeof RepertoireRepertoireId_DotchildrenDotnewRouteImport
      parentRoute: typeof RepertoireRoute
    }
    '/repertoire/$repertoireId_/excerpts/new': {
      id: '/repertoire/$repertoireId_/excerpts/new'
      path: '/$repertoireId/excerpts/new'
      fullPath: '/repertoire/$repertoireId/excerpts/new'
      preLoaderRoute: typeof RepertoireRepertoireId_DotexcerptsDotnewRouteImport
      parentRoute: typeof RepertoireRoute
    }
  }
}

interface ExercisesRouteChildren {
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  ExercisesNewRoute: typeof ExercisesNewRoute
  ExercisesOwnedRoute: typeof ExercisesOwnedRoute
  ExercisesSearchRoute: typeof ExercisesSearchRoute
  ExercisesExerciseId_DoteditRoute: typeof ExercisesExerciseId_DoteditRoute
}

const ExercisesRouteChildren: ExercisesRouteChildren = {
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  ExercisesNewRoute: ExercisesNewRoute,
  ExercisesOwnedRoute: ExercisesOwnedRoute,
  ExercisesSearchRoute: ExercisesSearchRoute,
  ExercisesExerciseId_DoteditRoute: ExercisesExerciseId_DoteditRoute,
}

const ExercisesRouteWithChildren = ExercisesRoute._addFileChildren(
  ExercisesRouteChildren,
)

interface RepertoireRouteChildren {
  RepertoireRepertoireIdRoute: typeof RepertoireRepertoireIdRoute
  RepertoireOwnedRoute: typeof RepertoireOwnedRoute
  RepertoireSearchRoute: typeof RepertoireSearchRoute
  RepertoireRepertoireId_DoteditRoute: typeof RepertoireRepertoireId_DoteditRoute
  RepertoireRepertoireId_DotchildrenDotnewRoute: typeof RepertoireRepertoireId_DotchildrenDotnewRoute
  RepertoireRepertoireId_DotexcerptsDotnewRoute: typeof RepertoireRepertoireId_DotexcerptsDotnewRoute
}

const RepertoireRouteChildren: RepertoireRouteChildren = {
  RepertoireRepertoireIdRoute: RepertoireRepertoireIdRoute,
  RepertoireOwnedRoute: RepertoireOwnedRoute,
  RepertoireSearchRoute: RepertoireSearchRoute,
  RepertoireRepertoireId_DoteditRoute: RepertoireRepertoireId_DoteditRoute,
  RepertoireRepertoireId_DotchildrenDotnewRoute:
    RepertoireRepertoireId_DotchildrenDotnewRoute,
  RepertoireRepertoireId_DotexcerptsDotnewRoute:
    RepertoireRepertoireId_DotexcerptsDotnewRoute,
}

const RepertoireRouteWithChildren = RepertoireRoute._addFileChildren(
  RepertoireRouteChildren,
)

interface SessionsRouteChildren {
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsNewRoute: typeof SessionsNewRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SessionsSessionId_DoteditRoute: typeof SessionsSessionId_DoteditRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsNewRoute: SessionsNewRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SessionsSessionId_DoteditRoute: SessionsSessionId_DoteditRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  TemplatesNewRoute: typeof TemplatesNewRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TemplatesTemplateId_DoteditRoute: typeof TemplatesTemplateId_DoteditRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  TemplatesNewRoute: TemplatesNewRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  TemplatesTemplateId_DoteditRoute: TemplatesTemplateId_DoteditRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesRoute: ExercisesRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  RepertoireRoute: RepertoireRouteWithChildren,
  SessionsRoute: SessionsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
